/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields  -IC:\nim-0.18.0\lib -o C:\SpaceRLTextEngine\src\crew\nimcache\captain.o C:\SpaceRLTextEngine\src\crew\nimcache\captain.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg;
typedef struct tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_kckNriGGAzuP8IWHI6ahWQ tySequence_kckNriGGAzuP8IWHI6ahWQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_UrZDrNVEOSGq4G9cScOVZbA tyTuple_UrZDrNVEOSGq4G9cScOVZbA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_PersonalityType_p8aLfub4VgJk2hYxvcDxPg;
struct tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ {
NimStringDesc* name;
NI experience;
NI level;
tyEnum_PersonalityType_p8aLfub4VgJk2hYxvcDxPg personalityType;
};
typedef NU8 tyEnum_SpecialAbility_Nfq9bTyAy0DTsLF9aqyxKoOA;
struct tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg {
tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ baseInfo;
NI captainAbility;
tyEnum_SpecialAbility_Nfq9bTyAy0DTsLF9aqyxKoOA specialAbility;
tySequence_kckNriGGAzuP8IWHI6ahWQ* secondaryAbilities;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_SecondaryAbility_KERPfdPSHO7fV1dgoEuvVw;
struct tyTuple_UrZDrNVEOSGq4G9cScOVZbA {
tyEnum_SecondaryAbility_KERPfdPSHO7fV1dgoEuvVw Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_kckNriGGAzuP8IWHI6ahWQ {
  TGenericSeq Sup;
  tyTuple_UrZDrNVEOSGq4G9cScOVZbA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*, generateCaptain_4xMZYa726gATSEXOnNuHrQ)(void);
static N_NIMCALL(void, Marker_tySequence_kckNriGGAzuP8IWHI6ahWQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_5rdQqe9cKjfum4W09bCKVdbA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, generateBaseCrewInfo_5oIh6C3nwqdQTBI9b9ayR02g)(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ* Result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_NIMCALL(void, TM_9c1WuqTwQTKeZ1Sc7cOOHAw_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, reprAny)(void* p, TNimType* typ);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_crewInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_crewDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, captainDatInit000)(void);
TNimType NTI_Rs1Hf5WKTvbgi6MF9cABhAg_;
extern TNimType NTI_EcJ9c5YFltk9a470QjqYqa9cQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_;
TNimType NTI_UrZDrNVEOSGq4G9cScOVZbA_;
extern TNimType NTI_KERPfdPSHO7fV1dgoEuvVw_;
TNimType NTI_kckNriGGAzuP8IWHI6ahWQ_;
TNimType NTI_5rdQqe9cKjfum4W09bCKVdbA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg* newCaptain_DVNVJ70P8FEwx0qvktI7cw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
static N_NIMCALL(void, Marker_tySequence_kckNriGGAzuP8IWHI6ahWQ)(void* p, NI op) {
	tySequence_kckNriGGAzuP8IWHI6ahWQ* a;
	NI T1_;
	a = (tySequence_kckNriGGAzuP8IWHI6ahWQ*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tyRef_5rdQqe9cKjfum4W09bCKVdbA)(void* p, NI op) {
	tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg* a;
	a = (tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*)p;
	nimGCvisit((void*)(*a).baseInfo.name, op);
	nimGCvisit((void*)(*a).secondaryAbilities, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*, generateCaptain_4xMZYa726gATSEXOnNuHrQ)(void) {
	tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg* result;
	tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg* T1_;
	nimfr_("generateCaptain", "captain.nim");
	result = (tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*)0;
	nimln_(12, "captain.nim");
	T1_ = (tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*)0;
	T1_ = (tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*) newObj((&NTI_5rdQqe9cKjfum4W09bCKVdbA_), sizeof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg));
	nimln_(13, "captain.nim");
	generateBaseCrewInfo_5oIh6C3nwqdQTBI9b9ayR02g((&(*T1_).baseInfo));
	result = T1_;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_9c1WuqTwQTKeZ1Sc7cOOHAw_4)(void) {
	nimGCvisit((void*)newCaptain_DVNVJ70P8FEwx0qvktI7cw, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	unknown_crewDatInit000();
	captainDatInit000();
	unknown_crewInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	nimfr_("captain", "captain.nim");
nimRegisterGlobalMarker(TM_9c1WuqTwQTKeZ1Sc7cOOHAw_4);
	nimln_(18, "captain.nim");
	asgnRefNoCycle((void**) (&newCaptain_DVNVJ70P8FEwx0qvktI7cw), generateCaptain_4xMZYa726gATSEXOnNuHrQ());
	nimln_(19, "captain.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = reprAny((&(*newCaptain_DVNVJ70P8FEwx0qvktI7cw).baseInfo), (&NTI_EcJ9c5YFltk9a470QjqYqa9cQ_));
	echoBinSafe(T1_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, captainDatInit000)(void) {
static TNimNode* TM_9c1WuqTwQTKeZ1Sc7cOOHAw_2[4];
static TNimNode* TM_9c1WuqTwQTKeZ1Sc7cOOHAw_3[2];
static TNimNode TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[8];
NTI_Rs1Hf5WKTvbgi6MF9cABhAg_.size = sizeof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg);
NTI_Rs1Hf5WKTvbgi6MF9cABhAg_.kind = 18;
NTI_Rs1Hf5WKTvbgi6MF9cABhAg_.base = 0;
NTI_Rs1Hf5WKTvbgi6MF9cABhAg_.flags = 2;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_2[0] = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[1];
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[1].kind = 1;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[1].offset = offsetof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg, baseInfo);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[1].typ = (&NTI_EcJ9c5YFltk9a470QjqYqa9cQ_);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[1].name = "baseInfo";
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_2[1] = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[2];
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[2].kind = 1;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[2].offset = offsetof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg, captainAbility);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[2].name = "captainAbility";
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_2[2] = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[3];
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[3].kind = 1;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[3].offset = offsetof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg, specialAbility);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[3].typ = (&NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[3].name = "specialAbility";
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_2[3] = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[4];
NTI_UrZDrNVEOSGq4G9cScOVZbA_.size = sizeof(tyTuple_UrZDrNVEOSGq4G9cScOVZbA);
NTI_UrZDrNVEOSGq4G9cScOVZbA_.kind = 18;
NTI_UrZDrNVEOSGq4G9cScOVZbA_.base = 0;
NTI_UrZDrNVEOSGq4G9cScOVZbA_.flags = 3;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_3[0] = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[6];
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[6].kind = 1;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[6].offset = offsetof(tyTuple_UrZDrNVEOSGq4G9cScOVZbA, Field0);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[6].typ = (&NTI_KERPfdPSHO7fV1dgoEuvVw_);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[6].name = "Field0";
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_3[1] = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[7];
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[7].kind = 1;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[7].offset = offsetof(tyTuple_UrZDrNVEOSGq4G9cScOVZbA, Field1);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[7].name = "Field1";
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[5].len = 2; TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[5].kind = 2; TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[5].sons = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_3[0];
NTI_UrZDrNVEOSGq4G9cScOVZbA_.node = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[5];
NTI_kckNriGGAzuP8IWHI6ahWQ_.size = sizeof(tySequence_kckNriGGAzuP8IWHI6ahWQ*);
NTI_kckNriGGAzuP8IWHI6ahWQ_.kind = 24;
NTI_kckNriGGAzuP8IWHI6ahWQ_.base = (&NTI_UrZDrNVEOSGq4G9cScOVZbA_);
NTI_kckNriGGAzuP8IWHI6ahWQ_.flags = 2;
NTI_kckNriGGAzuP8IWHI6ahWQ_.marker = Marker_tySequence_kckNriGGAzuP8IWHI6ahWQ;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[4].kind = 1;
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[4].offset = offsetof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg, secondaryAbilities);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[4].typ = (&NTI_kckNriGGAzuP8IWHI6ahWQ_);
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[4].name = "secondaryAbilities";
TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[0].len = 4; TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[0].kind = 2; TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[0].sons = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_2[0];
NTI_Rs1Hf5WKTvbgi6MF9cABhAg_.node = &TM_9c1WuqTwQTKeZ1Sc7cOOHAw_0[0];
NTI_5rdQqe9cKjfum4W09bCKVdbA_.size = sizeof(tyObject_CaptaincolonObjectType__Rs1Hf5WKTvbgi6MF9cABhAg*);
NTI_5rdQqe9cKjfum4W09bCKVdbA_.kind = 22;
NTI_5rdQqe9cKjfum4W09bCKVdbA_.base = (&NTI_Rs1Hf5WKTvbgi6MF9cABhAg_);
NTI_5rdQqe9cKjfum4W09bCKVdbA_.flags = 2;
NTI_5rdQqe9cKjfum4W09bCKVdbA_.marker = Marker_tyRef_5rdQqe9cKjfum4W09bCKVdbA;
}

