/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields  -IC:\nim-0.18.0\lib -o C:\SpaceRLTextEngine\src\crew\nimcache\crew.o C:\SpaceRLTextEngine\src\crew\nimcache\crew.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_PersonalityType_p8aLfub4VgJk2hYxvcDxPg;
struct tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ {
NimStringDesc* name;
NI experience;
NI level;
tyEnum_PersonalityType_p8aLfub4VgJk2hYxvcDxPg personalityType;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_SpecialAbility_Nfq9bTyAy0DTsLF9aqyxKoOA;
typedef NU8 tyEnum_SecondaryAbility_KERPfdPSHO7fV1dgoEuvVw;
N_LIB_PRIVATE N_NIMCALL(void, generateBaseCrewInfo_5oIh6C3nwqdQTBI9b9ayR02g)(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_EcJ9c5YFltk9a470QjqYqa9cQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_p8aLfub4VgJk2hYxvcDxPg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_;
TNimType NTI_KERPfdPSHO7fV1dgoEuvVw_;
STRING_LITERAL(TM_4pYDEDthCHvudLEYQPfAaw_6, "Kirk", 4);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, generateBaseCrewInfo_5oIh6C3nwqdQTBI9b9ayR02g)(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ* Result) {
	nimfr_("generateBaseCrewInfo", "crew.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_EcJ9c5YFltk9a470QjqYqa9cQ_));
	nimln_(30, "crew.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_EcJ9c5YFltk9a470QjqYqa9cQ_));
	unsureAsgnRef((void**) (&(*Result).name), copyString(((NimStringDesc*) &TM_4pYDEDthCHvudLEYQPfAaw_6)));
	(*Result).experience = ((NI) 0);
	(*Result).level = ((NI) 1);
	(*Result).personalityType = ((tyEnum_PersonalityType_p8aLfub4VgJk2hYxvcDxPg) 0);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_crewInit000)(void) {
	nimfr_("crew", "crew.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_crewDatInit000)(void) {
static TNimNode* TM_4pYDEDthCHvudLEYQPfAaw_2[4];
static TNimNode* TM_4pYDEDthCHvudLEYQPfAaw_3[5];
NI TM_4pYDEDthCHvudLEYQPfAaw_5;
static char* NIM_CONST TM_4pYDEDthCHvudLEYQPfAaw_4[5] = {
"ptA", 
"ptB", 
"ptC", 
"ptD", 
"ptE"};
static TNimNode* TM_4pYDEDthCHvudLEYQPfAaw_7[1];
NI TM_4pYDEDthCHvudLEYQPfAaw_9;
static char* NIM_CONST TM_4pYDEDthCHvudLEYQPfAaw_8[1] = {
"asNone"};
static TNimNode* TM_4pYDEDthCHvudLEYQPfAaw_10[6];
NI TM_4pYDEDthCHvudLEYQPfAaw_12;
static char* NIM_CONST TM_4pYDEDthCHvudLEYQPfAaw_11[6] = {
"saEngineering", 
"saScience", 
"saWeapons", 
"saHelm", 
"saMedical", 
"saCommunications"};
static TNimNode TM_4pYDEDthCHvudLEYQPfAaw_0[20];
NTI_EcJ9c5YFltk9a470QjqYqa9cQ_.size = sizeof(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ);
NTI_EcJ9c5YFltk9a470QjqYqa9cQ_.kind = 18;
NTI_EcJ9c5YFltk9a470QjqYqa9cQ_.base = 0;
NTI_EcJ9c5YFltk9a470QjqYqa9cQ_.flags = 2;
TM_4pYDEDthCHvudLEYQPfAaw_2[0] = &TM_4pYDEDthCHvudLEYQPfAaw_0[1];
TM_4pYDEDthCHvudLEYQPfAaw_0[1].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[1].offset = offsetof(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ, name);
TM_4pYDEDthCHvudLEYQPfAaw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4pYDEDthCHvudLEYQPfAaw_0[1].name = "name";
TM_4pYDEDthCHvudLEYQPfAaw_2[1] = &TM_4pYDEDthCHvudLEYQPfAaw_0[2];
TM_4pYDEDthCHvudLEYQPfAaw_0[2].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[2].offset = offsetof(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ, experience);
TM_4pYDEDthCHvudLEYQPfAaw_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4pYDEDthCHvudLEYQPfAaw_0[2].name = "experience";
TM_4pYDEDthCHvudLEYQPfAaw_2[2] = &TM_4pYDEDthCHvudLEYQPfAaw_0[3];
TM_4pYDEDthCHvudLEYQPfAaw_0[3].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[3].offset = offsetof(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ, level);
TM_4pYDEDthCHvudLEYQPfAaw_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4pYDEDthCHvudLEYQPfAaw_0[3].name = "level";
TM_4pYDEDthCHvudLEYQPfAaw_2[3] = &TM_4pYDEDthCHvudLEYQPfAaw_0[4];
NTI_p8aLfub4VgJk2hYxvcDxPg_.size = sizeof(tyEnum_PersonalityType_p8aLfub4VgJk2hYxvcDxPg);
NTI_p8aLfub4VgJk2hYxvcDxPg_.kind = 14;
NTI_p8aLfub4VgJk2hYxvcDxPg_.base = 0;
NTI_p8aLfub4VgJk2hYxvcDxPg_.flags = 3;
for (TM_4pYDEDthCHvudLEYQPfAaw_5 = 0; TM_4pYDEDthCHvudLEYQPfAaw_5 < 5; TM_4pYDEDthCHvudLEYQPfAaw_5++) {
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_5+5].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_5+5].offset = TM_4pYDEDthCHvudLEYQPfAaw_5;
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_5+5].name = TM_4pYDEDthCHvudLEYQPfAaw_4[TM_4pYDEDthCHvudLEYQPfAaw_5];
TM_4pYDEDthCHvudLEYQPfAaw_3[TM_4pYDEDthCHvudLEYQPfAaw_5] = &TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_5+5];
}
TM_4pYDEDthCHvudLEYQPfAaw_0[10].len = 5; TM_4pYDEDthCHvudLEYQPfAaw_0[10].kind = 2; TM_4pYDEDthCHvudLEYQPfAaw_0[10].sons = &TM_4pYDEDthCHvudLEYQPfAaw_3[0];
NTI_p8aLfub4VgJk2hYxvcDxPg_.node = &TM_4pYDEDthCHvudLEYQPfAaw_0[10];
TM_4pYDEDthCHvudLEYQPfAaw_0[4].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[4].offset = offsetof(tyObject_BaseCrewInfo_EcJ9c5YFltk9a470QjqYqa9cQ, personalityType);
TM_4pYDEDthCHvudLEYQPfAaw_0[4].typ = (&NTI_p8aLfub4VgJk2hYxvcDxPg_);
TM_4pYDEDthCHvudLEYQPfAaw_0[4].name = "personalityType";
TM_4pYDEDthCHvudLEYQPfAaw_0[0].len = 4; TM_4pYDEDthCHvudLEYQPfAaw_0[0].kind = 2; TM_4pYDEDthCHvudLEYQPfAaw_0[0].sons = &TM_4pYDEDthCHvudLEYQPfAaw_2[0];
NTI_EcJ9c5YFltk9a470QjqYqa9cQ_.node = &TM_4pYDEDthCHvudLEYQPfAaw_0[0];
NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_.size = sizeof(tyEnum_SpecialAbility_Nfq9bTyAy0DTsLF9aqyxKoOA);
NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_.kind = 14;
NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_.base = 0;
NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_.flags = 3;
for (TM_4pYDEDthCHvudLEYQPfAaw_9 = 0; TM_4pYDEDthCHvudLEYQPfAaw_9 < 1; TM_4pYDEDthCHvudLEYQPfAaw_9++) {
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_9+11].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_9+11].offset = TM_4pYDEDthCHvudLEYQPfAaw_9;
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_9+11].name = TM_4pYDEDthCHvudLEYQPfAaw_8[TM_4pYDEDthCHvudLEYQPfAaw_9];
TM_4pYDEDthCHvudLEYQPfAaw_7[TM_4pYDEDthCHvudLEYQPfAaw_9] = &TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_9+11];
}
TM_4pYDEDthCHvudLEYQPfAaw_0[12].len = 1; TM_4pYDEDthCHvudLEYQPfAaw_0[12].kind = 2; TM_4pYDEDthCHvudLEYQPfAaw_0[12].sons = &TM_4pYDEDthCHvudLEYQPfAaw_7[0];
NTI_Nfq9bTyAy0DTsLF9aqyxKoOA_.node = &TM_4pYDEDthCHvudLEYQPfAaw_0[12];
NTI_KERPfdPSHO7fV1dgoEuvVw_.size = sizeof(tyEnum_SecondaryAbility_KERPfdPSHO7fV1dgoEuvVw);
NTI_KERPfdPSHO7fV1dgoEuvVw_.kind = 14;
NTI_KERPfdPSHO7fV1dgoEuvVw_.base = 0;
NTI_KERPfdPSHO7fV1dgoEuvVw_.flags = 3;
for (TM_4pYDEDthCHvudLEYQPfAaw_12 = 0; TM_4pYDEDthCHvudLEYQPfAaw_12 < 6; TM_4pYDEDthCHvudLEYQPfAaw_12++) {
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_12+13].kind = 1;
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_12+13].offset = TM_4pYDEDthCHvudLEYQPfAaw_12;
TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_12+13].name = TM_4pYDEDthCHvudLEYQPfAaw_11[TM_4pYDEDthCHvudLEYQPfAaw_12];
TM_4pYDEDthCHvudLEYQPfAaw_10[TM_4pYDEDthCHvudLEYQPfAaw_12] = &TM_4pYDEDthCHvudLEYQPfAaw_0[TM_4pYDEDthCHvudLEYQPfAaw_12+13];
}
TM_4pYDEDthCHvudLEYQPfAaw_0[19].len = 6; TM_4pYDEDthCHvudLEYQPfAaw_0[19].kind = 2; TM_4pYDEDthCHvudLEYQPfAaw_0[19].sons = &TM_4pYDEDthCHvudLEYQPfAaw_10[0];
NTI_KERPfdPSHO7fV1dgoEuvVw_.node = &TM_4pYDEDthCHvudLEYQPfAaw_0[19];
}

