/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim-0.18.0\lib -o C:\SpaceRLTextEngine\src\nimcache\crew.o C:\SpaceRLTextEngine\src\nimcache\crew.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_Jtxj8YnZO9cu8mqaUBb1RtA tySequence_Jtxj8YnZO9cu8mqaUBb1RtA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ;
typedef struct tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA;
typedef struct tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog;
typedef struct tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ;
typedef struct tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA;
typedef struct tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w;
typedef struct tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q;
typedef struct tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw;
typedef struct tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A;
typedef struct tySequence_GAlN8CVr46NYIZ4im9c9baNw tySequence_GAlN8CVr46NYIZ4im9c9baNw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_hIfxrk3SgJbH9bl3niLBXLg tyTuple_hIfxrk3SgJbH9bl3niLBXLg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ {
NimStringDesc* firstName;
NimStringDesc* lastName;
NI experience;
NI level;
tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ personalityType;
};
struct tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA {
tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog* captain;
tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ* communications;
tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA* engineer;
tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w* medical;
tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q* navigation;
tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw* science;
tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg* tactical;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NU8 tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA;
struct tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI captainAbility;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
tySequence_GAlN8CVr46NYIZ4im9c9baNw* secondaryAbilities;
};
struct tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI diplomacy;
NI linguisticAbility;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI powerManagement;
NI Repair;
NI shipImprovements;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI surgicalAbility;
NI diseaseAnalysis;
NI scienceBonus;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI maneuvering;
NI courseSettings;
NI sublightSpeedModifier;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI exploration;
NI problemSolving;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI targetting;
NI shieldModulation;
NI security;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A {
NU64 a0;
NU64 a1;
};
typedef NU8 tyEnum_SecondaryAbility_dwHVYTQaEvrenavHYJmo6w;
struct tyTuple_hIfxrk3SgJbH9bl3niLBXLg {
tyEnum_SecondaryAbility_dwHVYTQaEvrenavHYJmo6w Field0;
NI Field1;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Jtxj8YnZO9cu8mqaUBb1RtA {
  TGenericSeq Sup;
  tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ data[SEQ_DECL_SIZE];
};
struct tySequence_GAlN8CVr46NYIZ4im9c9baNw {
  TGenericSeq Sup;
  tyTuple_hIfxrk3SgJbH9bl3niLBXLg data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, generateFirstName_hmifkXHmi3cNB1EPx0g8Eg)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, generateLastName_hmifkXHmi3cNB1EPx0g8Eg_2)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ, generatePersonalityType_XS9c9acPzdfcVeXPR55bhlQA)(void);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ, rand_PcJft7w0FmlF27beget4GQ)(tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ* a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(void, generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA*, generateCrew_VMtMhfVktk0mjWNY9cwADPg)(void);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog*, generateCaptain_bJdC9bwcxW0CoAya1uM31FA)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ*, generateCommunicationsOfficer_EF9cuDLp9bDwPtK9b1CL9cy83Q)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
N_LIB_PRIVATE N_NIMCALL(tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA*, generateEngineeringOfficer_Z0efkGtOlMCMWrbK6N07Rw)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
N_LIB_PRIVATE N_NIMCALL(tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w*, generateMedicalOfficer_YMb9cBYvIZbFRVWU2s55VPw)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
N_LIB_PRIVATE N_NIMCALL(tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q*, generateNavigationOfficer_ksohtDr9a1dAL8lDDhskAvQ)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
N_LIB_PRIVATE N_NIMCALL(tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw*, generateScienceOfficer_V3UIwQyRth70mCYQh0sqNA)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
N_LIB_PRIVATE N_NIMCALL(tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg*, generateTacticalOfficer_mFlBFfOCjuyT9ayBO4ygTBQ)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* baseCrewInfo);
N_LIB_PRIVATE N_NIMCALL(NI, rand_an9ajRjsC0saLyxF46lqhIw)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
N_LIB_PRIVATE N_NIMCALL(NI, rand_llsvpw3XcUUMY9bBfAwkSMg)(tyObject_Rand_liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_Jtxj8YnZO9cu8mqaUBb1RtA_;
extern TNimType NTI_XKHobPLd3O3l3A9aqud8UbQ_;
extern TNimType NTI_Sp6bXpfmbsi9bgPZoqsvJIQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_4pYDEDthCHvudLEYQPfAaw_2, "Jim", 3);
STRING_LITERAL(TM_4pYDEDthCHvudLEYQPfAaw_3, "Kirk", 4);
NIM_CONST struct {
  TGenericSeq Sup;
  tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ data[5];
} TM_4pYDEDthCHvudLEYQPfAaw_5 = {{5, 5}, {((tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ) 0),
((tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ) 1),
((tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ) 2),
((tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ) 3),
((tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ) 4)}};
NIM_CONST tySequence_Jtxj8YnZO9cu8mqaUBb1RtA* TM_4pYDEDthCHvudLEYQPfAaw_4 = ((tySequence_Jtxj8YnZO9cu8mqaUBb1RtA*)&TM_4pYDEDthCHvudLEYQPfAaw_5);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, generateFirstName_hmifkXHmi3cNB1EPx0g8Eg)(void) {
	NimStringDesc* result;
	nimfr_("generateFirstName", "crew.nim");
	result = (NimStringDesc*)0;
	nimln_(15, "crew.nim");
	result = copyString(((NimStringDesc*) &TM_4pYDEDthCHvudLEYQPfAaw_2));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, generateLastName_hmifkXHmi3cNB1EPx0g8Eg_2)(void) {
	NimStringDesc* result;
	nimfr_("generateLastName", "crew.nim");
	result = (NimStringDesc*)0;
	nimln_(18, "crew.nim");
	result = copyString(((NimStringDesc*) &TM_4pYDEDthCHvudLEYQPfAaw_3));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ, generatePersonalityType_XS9c9acPzdfcVeXPR55bhlQA)(void) {
	tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ result;
	tySequence_Jtxj8YnZO9cu8mqaUBb1RtA* personalities;
	nimfr_("generatePersonalityType", "crew.nim");
{	result = (tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ)0;
	nimln_(21, "crew.nim");
	genericSeqAssign((&personalities), TM_4pYDEDthCHvudLEYQPfAaw_4, (&NTI_Jtxj8YnZO9cu8mqaUBb1RtA_));
	nimln_(22, "crew.nim");
	result = rand_PcJft7w0FmlF27beget4GQ(personalities->data, personalities->Sup.len);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ)(tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ* Result) {
	nimfr_("generateBaseCrewInfo", "crew.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_XKHobPLd3O3l3A9aqud8UbQ_));
	nimln_(25, "crew.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_XKHobPLd3O3l3A9aqud8UbQ_));
	nimln_(26, "crew.nim");
	unsureAsgnRef((void**) (&(*Result).firstName), generateFirstName_hmifkXHmi3cNB1EPx0g8Eg());
	nimln_(27, "crew.nim");
	unsureAsgnRef((void**) (&(*Result).lastName), generateLastName_hmifkXHmi3cNB1EPx0g8Eg_2());
	(*Result).experience = ((NI) 0);
	(*Result).level = ((NI) 1);
	nimln_(30, "crew.nim");
	(*Result).personalityType = generatePersonalityType_XS9c9acPzdfcVeXPR55bhlQA();
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA*, generateCrew_VMtMhfVktk0mjWNY9cwADPg)(void) {
	tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA* result;
	tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA* T1_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T2_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T3_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T4_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T5_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T6_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T7_;
	tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ T8_;
	nimfr_("generateCrew", "crew.nim");
	result = (tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA*)0;
	nimln_(35, "crew.nim");
	T1_ = (tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA*)0;
	T1_ = (tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA*) newObj((&NTI_Sp6bXpfmbsi9bgPZoqsvJIQ_), sizeof(tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA));
	nimln_(36, "crew.nim");
	memset((void*)(&T2_), 0, sizeof(T2_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T2_));
	asgnRefNoCycle((void**) (&(*T1_).captain), generateCaptain_bJdC9bwcxW0CoAya1uM31FA((&T2_)));
	nimln_(37, "crew.nim");
	memset((void*)(&T3_), 0, sizeof(T3_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T3_));
	asgnRefNoCycle((void**) (&(*T1_).communications), generateCommunicationsOfficer_EF9cuDLp9bDwPtK9b1CL9cy83Q((&T3_)));
	nimln_(38, "crew.nim");
	memset((void*)(&T4_), 0, sizeof(T4_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T4_));
	asgnRefNoCycle((void**) (&(*T1_).engineer), generateEngineeringOfficer_Z0efkGtOlMCMWrbK6N07Rw((&T4_)));
	nimln_(39, "crew.nim");
	memset((void*)(&T5_), 0, sizeof(T5_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T5_));
	asgnRefNoCycle((void**) (&(*T1_).medical), generateMedicalOfficer_YMb9cBYvIZbFRVWU2s55VPw((&T5_)));
	nimln_(40, "crew.nim");
	memset((void*)(&T6_), 0, sizeof(T6_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T6_));
	asgnRefNoCycle((void**) (&(*T1_).navigation), generateNavigationOfficer_ksohtDr9a1dAL8lDDhskAvQ((&T6_)));
	nimln_(41, "crew.nim");
	memset((void*)(&T7_), 0, sizeof(T7_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T7_));
	asgnRefNoCycle((void**) (&(*T1_).science), generateScienceOfficer_V3UIwQyRth70mCYQh0sqNA((&T7_)));
	nimln_(42, "crew.nim");
	memset((void*)(&T8_), 0, sizeof(T8_));
	generateBaseCrewInfo_zJJ9c86cbn1MP33iOs832AQ((&T8_));
	asgnRefNoCycle((void**) (&(*T1_).tactical), generateTacticalOfficer_mFlBFfOCjuyT9ayBO4ygTBQ((&T8_)));
	result = T1_;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_crewInit000)(void) {
	nimfr_("crew", "crew.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_crewDatInit000)(void) {
}

