/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim-0.18.0\lib -o C:\SpaceRLTextEngine\src\nimcache\main.o C:\SpaceRLTextEngine\src\nimcache\main.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog;
typedef struct tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ;
typedef struct tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA;
typedef struct tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w;
typedef struct tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q;
typedef struct tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw;
typedef struct tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ;
typedef struct tySequence_GAlN8CVr46NYIZ4im9c9baNw tySequence_GAlN8CVr46NYIZ4im9c9baNw;
typedef struct tyTuple_hIfxrk3SgJbH9bl3niLBXLg tyTuple_hIfxrk3SgJbH9bl3niLBXLg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA {
tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog* captain;
tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ* communications;
tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA* engineer;
tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w* medical;
tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q* navigation;
tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw* science;
tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg* tactical;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef NU8 tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ;
struct tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ {
NimStringDesc* firstName;
NimStringDesc* lastName;
NI experience;
NI level;
tyEnum_PersonalityType_gdWQV5cGkpq7KxGxo9aIyQQ personalityType;
};
typedef NU8 tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA;
struct tyObject_CaptaincolonObjectType__ayQkAUqJ29c1309alQMzvTog {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI captainAbility;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
tySequence_GAlN8CVr46NYIZ4im9c9baNw* secondaryAbilities;
};
struct tyObject_CommunicationsOfficercolonObjectType__wnFlv9aO9aNGi3o5MybXAQyQ {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI diplomacy;
NI linguisticAbility;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_EngineeringOfficercolonObjectType__8liM6t47WLrUSyikv8cHkA {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI powerManagement;
NI Repair;
NI shipImprovements;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_MedicalOfficercolonObjectType__C9c0kCMAVqkylAo9bZzRDI5w {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI surgicalAbility;
NI diseaseAnalysis;
NI scienceBonus;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_NavigationOfficercolonObjectType__2TU9cTQpfMOQw06LCgDZx3Q {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI maneuvering;
NI courseSettings;
NI sublightSpeedModifier;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_ScienceOfficercolonObjectType__fSGVZJXYXAS4sa5877WqRw {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI exploration;
NI problemSolving;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_TacticalOfficercolonObjectType__cMpUz7QL6IsA9ckWvxIV9a9cg {
tyObject_BaseCrewInfo_XKHobPLd3O3l3A9aqud8UbQ baseInfo;
NI targetting;
NI shieldModulation;
NI security;
tyEnum_SpecialAbility_hx7wZOTzQdLuVhirIVcmYA specialAbility;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
typedef NU8 tyEnum_SecondaryAbility_dwHVYTQaEvrenavHYJmo6w;
struct tyTuple_hIfxrk3SgJbH9bl3niLBXLg {
tyEnum_SecondaryAbility_dwHVYTQaEvrenavHYJmo6w Field0;
NI Field1;
};
struct tySequence_GAlN8CVr46NYIZ4im9c9baNw {
  TGenericSeq Sup;
  tyTuple_hIfxrk3SgJbH9bl3niLBXLg data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, randomize_RtUZt2O8eA6Y5pFWOsdgjg)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA*, generateCrew_VMtMhfVktk0mjWNY9cwADPg)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, reprAny)(void* p, TNimType* typ);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_randomDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_crewtypesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_crewtypesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_captainInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_captainDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_communicationsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_communicationsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_engineerInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_engineerDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_medicalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_medicalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_navigationInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_navigationDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_scienceInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_scienceDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_tacticalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_tacticalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_crewInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_crewDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
tyObject_ShipCrewcolonObjectType__ROIq9bhCLaVdyWYbjv0VWAA* newCrew_Fr7coNTFoBWN2YkRLm1Fag;
extern TNimType NTI_Sp6bXpfmbsi9bgPZoqsvJIQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_ZIWF3RAPbylxlKADfMpcCw_;
extern TNimType NTI_9b9bLL9aVzoJ5c0S8E9ajEDJXA_;
extern TNimType NTI_WVwu5lbbEGFe9bMbO9bJvyKQ_;
extern TNimType NTI_DgpHA2MoyK2hOMb2s4fWSw_;
extern TNimType NTI_9bn9cFcdfV2ORVXywWKHaRCg_;
extern TNimType NTI_PzqjnrSNOeItfuyXAztypw_;
extern TNimType NTI_l6gzlXC9az4Slw0mFMjpOXQ_;
static N_NIMCALL(void, TM_V45tF8B8NBcxFcjfe7lhBw_2)(void) {
	nimGCvisit((void*)newCrew_Fr7coNTFoBWN2YkRLm1Fag, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_randomDatInit000();
	unknown_crewtypesDatInit000();
	unknown_captainDatInit000();
	unknown_communicationsDatInit000();
	unknown_engineerDatInit000();
	unknown_medicalDatInit000();
	unknown_navigationDatInit000();
	unknown_scienceDatInit000();
	unknown_tacticalDatInit000();
	unknown_crewDatInit000();
	mainDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_randomInit000();
	unknown_crewtypesInit000();
	unknown_captainInit000();
	unknown_communicationsInit000();
	unknown_engineerInit000();
	unknown_medicalInit000();
	unknown_navigationInit000();
	unknown_scienceInit000();
	unknown_tacticalInit000();
	unknown_crewInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T4_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T7_;
	nimfr_("main", "main.nim");
nimRegisterGlobalMarker(TM_V45tF8B8NBcxFcjfe7lhBw_2);
	nimln_(5, "main.nim");
	randomize_RtUZt2O8eA6Y5pFWOsdgjg();
	nimln_(6, "main.nim");
	asgnRefNoCycle((void**) (&newCrew_Fr7coNTFoBWN2YkRLm1Fag), generateCrew_VMtMhfVktk0mjWNY9cwADPg());
	nimln_(7, "main.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).captain, (&NTI_ZIWF3RAPbylxlKADfMpcCw_));
	echoBinSafe(T1_, 1);
	nimln_(8, "main.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	T2_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).communications, (&NTI_9b9bLL9aVzoJ5c0S8E9ajEDJXA_));
	echoBinSafe(T2_, 1);
	nimln_(9, "main.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).engineer, (&NTI_WVwu5lbbEGFe9bMbO9bJvyKQ_));
	echoBinSafe(T3_, 1);
	nimln_(10, "main.nim");
	memset((void*)T4_, 0, sizeof(T4_));
	T4_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).medical, (&NTI_DgpHA2MoyK2hOMb2s4fWSw_));
	echoBinSafe(T4_, 1);
	nimln_(11, "main.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	T5_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).navigation, (&NTI_9bn9cFcdfV2ORVXywWKHaRCg_));
	echoBinSafe(T5_, 1);
	nimln_(12, "main.nim");
	memset((void*)T6_, 0, sizeof(T6_));
	T6_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).science, (&NTI_PzqjnrSNOeItfuyXAztypw_));
	echoBinSafe(T6_, 1);
	nimln_(13, "main.nim");
	memset((void*)T7_, 0, sizeof(T7_));
	T7_[0] = reprAny((*newCrew_Fr7coNTFoBWN2YkRLm1Fag).tactical, (&NTI_l6gzlXC9az4Slw0mFMjpOXQ_));
	echoBinSafe(T7_, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

