/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim-0.18.0\lib -o C:\SpaceRLTextEngine\src\nimcache\settings.o C:\SpaceRLTextEngine\src\nimcache\settings.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_awOivLjlO76sGdHY7nQUjQ tyTuple_awOivLjlO76sGdHY7nQUjQ;
struct tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug {
tySequence_8Np6tlClE5az1CyqZdN19bQ* personalityModifiers;
tySequence_8Np6tlClE5az1CyqZdN19bQ* abilityModifiers;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence_8Np6tlClE5az1CyqZdN19bQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_xHqxgsw1DP8hsrmYmBQMPQ)(void* p, NI op);
static N_NIMCALL(void, TM_k3uWuteRAUF0aC9bYK8DHdQ_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, initSettings_f9ajm7lbLRBEMeNaZ9c8AdfQ)(void);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseFile_jHjkbBWx0TRN9bcGqTg49c4A)(NimStringDesc* filename);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NI, getInt_rDQb9chpfbduaO7rsIalSMw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NI default_0);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NI index);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*, getSettings_01cqgTepOwZPpeTd0L7zBA)(void);
N_NIMCALL(NimStringDesc*, reprAny)(void* p, TNimType* typ);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug* gameSettings_YufBwRpDyBPU0j8mS59cVEg;
TNimType NTI_BUU28bFoXVHi5UM6kVXYug_;
TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_8Np6tlClE5az1CyqZdN19bQ_;
TNimType NTI_xHqxgsw1DP8hsrmYmBQMPQ_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_5, "../settings.json", 16);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_6, "not isNil(node) ", 16);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_7, "node.kind == JObject ", 21);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_8, "fields", 6);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_9, "abilityModifiers", 16);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_10, "node.kind == JArray ", 20);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_11, "elems", 5);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_13, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_k3uWuteRAUF0aC9bYK8DHdQ_14, "personalityModifiers", 20);
static N_NIMCALL(void, Marker_tySequence_8Np6tlClE5az1CyqZdN19bQ)(void* p, NI op) {
	tySequence_8Np6tlClE5az1CyqZdN19bQ* a;
	NI T1_;
	a = (tySequence_8Np6tlClE5az1CyqZdN19bQ*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tyRef_xHqxgsw1DP8hsrmYmBQMPQ)(void* p, NI op) {
	tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug* a;
	a = (tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*)p;
	nimGCvisit((void*)(*a).personalityModifiers, op);
	nimGCvisit((void*)(*a).abilityModifiers, op);
}
static N_NIMCALL(void, TM_k3uWuteRAUF0aC9bYK8DHdQ_4)(void) {
	nimGCvisit((void*)gameSettings_YufBwRpDyBPU0j8mS59cVEg, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q** T9_;
	nimfr_("[]", "json.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(920, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_6));
	}
	LA3_: ;
	nimln_(921, "json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_7));
	}
	LA7_: ;
	nimln_(924, "json.nim");
	if (!(((32 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_8));
	T9_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**)0;
	T9_ = X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg((&(*node).kindU.S6.fields), name);
	result = (*T9_);
	popFrame();
	return result;
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NI index) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	nimfr_("[]", "json.nim");
{	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(930, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_6));
	}
	LA3_: ;
	nimln_(931, "json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_10));
	}
	LA7_: ;
	nimln_(932, "json.nim");
	if (!(((64 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_11));
	if ((NU)(index) >= (NU)((*node).kindU.S7.elems->Sup.len)) raiseIndexError();
	result = (*node).kindU.S7.elems->data[index];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initSettings_f9ajm7lbLRBEMeNaZ9c8AdfQ)(void) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jsonConfig;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* abilityModsJson;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* personalityModsJson;
	nimfr_("initSettings", "settings.nim");
	nimln_(16, "settings.nim");
	if ((*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers) { nimGCunrefNoCycle((*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers); (*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers = NIM_NIL; }
	(*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers = (tySequence_8Np6tlClE5az1CyqZdN19bQ*) newSeqRC1((&NTI_8Np6tlClE5az1CyqZdN19bQ_), 0);
	nimln_(17, "settings.nim");
	if ((*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers) { nimGCunrefNoCycle((*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers); (*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers = NIM_NIL; }
	(*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers = (tySequence_8Np6tlClE5az1CyqZdN19bQ*) newSeqRC1((&NTI_8Np6tlClE5az1CyqZdN19bQ_), 0);
	nimln_(19, "settings.nim");
	jsonConfig = parseFile_jHjkbBWx0TRN9bcGqTg49c4A(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_5));
	nimln_(20, "settings.nim");
	abilityModsJson = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonConfig, ((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_9));
	{
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* ability;
		ability = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		nimln_(1159, "json.nim");
		{
			if (!!(((*abilityModsJson).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA4_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_10));
		}
		LA4_: ;
		{
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* i;
			tySequence_oLpBKXzW3hF9aCVMo5EymfQ* colontmp_;
			NI i_2;
			NI L;
			NI T7_;
			i = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			colontmp_ = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
			nimln_(1160, "json.nim");
			if (!(((64 &(1U<<((NU)((*abilityModsJson).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_11));
			colontmp_ = (*abilityModsJson).kindU.S7.elems;
			nimln_(3805, "system.nim");
			i_2 = ((NI) 0);
			nimln_(3806, "system.nim");
			T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
			L = T7_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI chance;
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T10_;
					NI modifier;
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T11_;
					tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ combo;
					NI T12_;
					NI TM_k3uWuteRAUF0aC9bYK8DHdQ_12;
					if (!(i_2 < L)) goto LA9;
					nimln_(3808, "system.nim");
					if ((NU)(i_2) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
					i = colontmp_->data[i_2];
					nimln_(1161, "json.nim");
					ability = i;
					nimln_(23, "settings.nim");
					T10_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
					T10_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(ability, ((NI) 0));
					chance = getInt_rDQb9chpfbduaO7rsIalSMw(T10_, ((NI) 0));
					nimln_(24, "settings.nim");
					T11_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
					T11_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(ability, ((NI) 1));
					modifier = getInt_rDQb9chpfbduaO7rsIalSMw(T11_, ((NI) 0));
					nimln_(25, "settings.nim");
					combo.Field0 = chance;
					combo.Field1 = modifier;
					nimln_(26, "settings.nim");
					(*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers = (tySequence_8Np6tlClE5az1CyqZdN19bQ*) incrSeqV2(&((*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers)->Sup, sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ));
					T12_ = (*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers->Sup.len++;
					(*gameSettings_YufBwRpDyBPU0j8mS59cVEg).abilityModifiers->data[T12_] = combo;
					nimln_(3809, "system.nim");
					TM_k3uWuteRAUF0aC9bYK8DHdQ_12 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_k3uWuteRAUF0aC9bYK8DHdQ_12);
					nimln_(3810, "system.nim");
					{
						NI T15_;
						T15_ = (colontmp_ ? colontmp_->Sup.len : 0);
						if (!!((T15_ == L))) goto LA16_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_13));
					}
					LA16_: ;
				} LA9: ;
			}
		}
	}
	nimln_(28, "settings.nim");
	personalityModsJson = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsonConfig, ((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_14));
	{
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* personality;
		personality = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		nimln_(1159, "json.nim");
		{
			if (!!(((*personalityModsJson).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA21_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_10));
		}
		LA21_: ;
		{
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* i_3;
			tySequence_oLpBKXzW3hF9aCVMo5EymfQ* colontmp__2;
			NI i_4;
			NI L_2;
			NI T24_;
			i_3 = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			colontmp__2 = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
			nimln_(1160, "json.nim");
			if (!(((64 &(1U<<((NU)((*personalityModsJson).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_11));
			colontmp__2 = (*personalityModsJson).kindU.S7.elems;
			nimln_(3805, "system.nim");
			i_4 = ((NI) 0);
			nimln_(3806, "system.nim");
			T24_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
			L_2 = T24_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI chance_2;
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T27_;
					NI modifier_2;
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T28_;
					tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ combo_2;
					NI T29_;
					NI TM_k3uWuteRAUF0aC9bYK8DHdQ_15;
					if (!(i_4 < L_2)) goto LA26;
					nimln_(3808, "system.nim");
					if ((NU)(i_4) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
					i_3 = colontmp__2->data[i_4];
					nimln_(1161, "json.nim");
					personality = i_3;
					nimln_(31, "settings.nim");
					T27_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
					T27_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(personality, ((NI) 0));
					chance_2 = getInt_rDQb9chpfbduaO7rsIalSMw(T27_, ((NI) 0));
					nimln_(32, "settings.nim");
					T28_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
					T28_ = X5BX5D__xDCGOmTeHqy9c9aFn6etpytwjson(personality, ((NI) 1));
					modifier_2 = getInt_rDQb9chpfbduaO7rsIalSMw(T28_, ((NI) 0));
					nimln_(33, "settings.nim");
					combo_2.Field0 = chance_2;
					combo_2.Field1 = modifier_2;
					nimln_(34, "settings.nim");
					(*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers = (tySequence_8Np6tlClE5az1CyqZdN19bQ*) incrSeqV2(&((*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers)->Sup, sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ));
					T29_ = (*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers->Sup.len++;
					(*gameSettings_YufBwRpDyBPU0j8mS59cVEg).personalityModifiers->data[T29_] = combo_2;
					nimln_(3809, "system.nim");
					TM_k3uWuteRAUF0aC9bYK8DHdQ_15 = addInt(i_4, ((NI) 1));
					i_4 = (NI)(TM_k3uWuteRAUF0aC9bYK8DHdQ_15);
					nimln_(3810, "system.nim");
					{
						NI T32_;
						T32_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
						if (!!((T32_ == L_2))) goto LA33_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_k3uWuteRAUF0aC9bYK8DHdQ_13));
					}
					LA33_: ;
				} LA26: ;
			}
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*, getSettings_01cqgTepOwZPpeTd0L7zBA)(void) {
	tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug* result;
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	nimfr_("getSettings", "settings.nim");
{	result = (tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*)0;
	nimln_(38, "settings.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = reprAny(gameSettings_YufBwRpDyBPU0j8mS59cVEg, (&NTI_xHqxgsw1DP8hsrmYmBQMPQ_));
	echoBinSafe(T1_, 1);
	nimln_(39, "settings.nim");
	result = gameSettings_YufBwRpDyBPU0j8mS59cVEg;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_settingsInit000)(void) {
	tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug* T1_;
	nimfr_("settings", "settings.nim");
nimRegisterGlobalMarker(TM_k3uWuteRAUF0aC9bYK8DHdQ_4);
	nimln_(13, "settings.nim");
	T1_ = (tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*)0;
	T1_ = (tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*) newObj((&NTI_xHqxgsw1DP8hsrmYmBQMPQ_), sizeof(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug));
	asgnRefNoCycle((void**) (&gameSettings_YufBwRpDyBPU0j8mS59cVEg), T1_);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_settingsDatInit000)(void) {
static TNimNode* TM_k3uWuteRAUF0aC9bYK8DHdQ_2[2];
static TNimNode* TM_k3uWuteRAUF0aC9bYK8DHdQ_3[2];
static TNimNode TM_k3uWuteRAUF0aC9bYK8DHdQ_0[6];
NTI_BUU28bFoXVHi5UM6kVXYug_.size = sizeof(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug);
NTI_BUU28bFoXVHi5UM6kVXYug_.kind = 18;
NTI_BUU28bFoXVHi5UM6kVXYug_.base = 0;
NTI_BUU28bFoXVHi5UM6kVXYug_.flags = 2;
TM_k3uWuteRAUF0aC9bYK8DHdQ_2[0] = &TM_k3uWuteRAUF0aC9bYK8DHdQ_0[1];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.size = sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.kind = 18;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.base = 0;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.flags = 3;
TM_k3uWuteRAUF0aC9bYK8DHdQ_3[0] = &TM_k3uWuteRAUF0aC9bYK8DHdQ_0[3];
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[3].kind = 1;
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[3].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field0);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[3].name = "Field0";
TM_k3uWuteRAUF0aC9bYK8DHdQ_3[1] = &TM_k3uWuteRAUF0aC9bYK8DHdQ_0[4];
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[4].kind = 1;
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[4].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field1);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[4].name = "Field1";
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[2].len = 2; TM_k3uWuteRAUF0aC9bYK8DHdQ_0[2].kind = 2; TM_k3uWuteRAUF0aC9bYK8DHdQ_0[2].sons = &TM_k3uWuteRAUF0aC9bYK8DHdQ_3[0];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.node = &TM_k3uWuteRAUF0aC9bYK8DHdQ_0[2];
NTI_8Np6tlClE5az1CyqZdN19bQ_.size = sizeof(tySequence_8Np6tlClE5az1CyqZdN19bQ*);
NTI_8Np6tlClE5az1CyqZdN19bQ_.kind = 24;
NTI_8Np6tlClE5az1CyqZdN19bQ_.base = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
NTI_8Np6tlClE5az1CyqZdN19bQ_.flags = 2;
NTI_8Np6tlClE5az1CyqZdN19bQ_.marker = Marker_tySequence_8Np6tlClE5az1CyqZdN19bQ;
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[1].kind = 1;
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[1].offset = offsetof(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug, personalityModifiers);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[1].typ = (&NTI_8Np6tlClE5az1CyqZdN19bQ_);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[1].name = "personalityModifiers";
TM_k3uWuteRAUF0aC9bYK8DHdQ_2[1] = &TM_k3uWuteRAUF0aC9bYK8DHdQ_0[5];
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[5].kind = 1;
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[5].offset = offsetof(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug, abilityModifiers);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[5].typ = (&NTI_8Np6tlClE5az1CyqZdN19bQ_);
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[5].name = "abilityModifiers";
TM_k3uWuteRAUF0aC9bYK8DHdQ_0[0].len = 2; TM_k3uWuteRAUF0aC9bYK8DHdQ_0[0].kind = 2; TM_k3uWuteRAUF0aC9bYK8DHdQ_0[0].sons = &TM_k3uWuteRAUF0aC9bYK8DHdQ_2[0];
NTI_BUU28bFoXVHi5UM6kVXYug_.node = &TM_k3uWuteRAUF0aC9bYK8DHdQ_0[0];
NTI_xHqxgsw1DP8hsrmYmBQMPQ_.size = sizeof(tyObject_GameSettingscolonObjectType__BUU28bFoXVHi5UM6kVXYug*);
NTI_xHqxgsw1DP8hsrmYmBQMPQ_.kind = 22;
NTI_xHqxgsw1DP8hsrmYmBQMPQ_.base = (&NTI_BUU28bFoXVHi5UM6kVXYug_);
NTI_xHqxgsw1DP8hsrmYmBQMPQ_.flags = 2;
NTI_xHqxgsw1DP8hsrmYmBQMPQ_.marker = Marker_tyRef_xHqxgsw1DP8hsrmYmBQMPQ;
}

