/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files\mingw64-6.3.0\mingw64\bin\gcc.exe" -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim-0.18.0\lib -o C:\SpaceRLTextEngine\src\nimcache\stdlib_parsecsv.o C:\SpaceRLTextEngine\src\nimcache\stdlib_parsecsv.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ;
typedef struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ {
  tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw {
  RootObj Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars;
};
struct tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ {
  tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* row;
NimStringDesc* filename;
NIM_CHAR sep;
NIM_CHAR quote;
NIM_CHAR esc;
NIM_BOOL skipWhite;
NI currRow;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* headers;
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
FILE* f;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, raiseEInvalidCsv_HcftpwJzOOP1xPgLVh0oUg)(NimStringDesc* filename, NI line, NI col, NimStringDesc* msg) __attribute__((noreturn));
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_VgLrzdOR3HwTOOL2IcFN9cA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, error_rSVZOSfuDbBAJ4HGxo0CdQ)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI pos, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber_9cj186ckGjLqyndkoW7bBdg)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, open_dmBuwTCvdiT9cdjydWhbTTg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
N_LIB_PRIVATE N_NIMCALL(void, open_xmgaYJZNnO6QcDtac9bs3Vg)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NI bufLen, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, open_grmoJIpX15R5Xfx6m2M1UA)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw*, newFileStream_9argyMqCIlB1KDaxUuYVcmw)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(void, parseField_dP4vy9acfqJXAsuKp69aq8eQ)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc** a);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR_IwUEvMBOLRY9cqyar6XKEaw_2)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF_IwUEvMBOLRY9cqyar6XKEaw_3)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, processedRows_B9bl8htcg8N29c8FQEl079aPg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readRow_9bHdhFE0qEvOrDqjuQBz8Pw)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI columns);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, close_A55CxARYHkQe359a6AS5GRQparsecsv)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_LIB_PRIVATE N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
N_LIB_PRIVATE N_NIMCALL(void, readHeaderRow_8SSmlmR2zJJf2vnae2Ozsw)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, rowEntry_A5sOKo5r9bzqQUyQAneitHg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* entry);
static N_INLINE(NI, find_sPsD5Eb3qBZqwDJ6Yy4sNQparsecsv)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* a, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
TNimType NTI_5MMHYN9cM2d1GsHy5O9agEIQ_;
TNimType NTI_VgLrzdOR3HwTOOL2IcFN9cA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_B6cGbTPhMsqMovc9cOcIHRw_;
TNimType NTI_e0KmhL4ItditGQKnCUZMoQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_nmiMWKVIe46vacnhAFrQvw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_2, "Error: ", 7);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_3, "(", 1);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_4, ", ", 2);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_5, ") Error: ", 9);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_3rBY6NOHI29c34PPPPzLAdQ_6 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_7, "cannot open: ", 13);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_10, " expected", 9);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_16, "\012", 1);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_21, "", 0);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_25, " columns expected, but found ", 29);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_26, " columns", 8);
STRING_LITERAL(TM_3rBY6NOHI29c34PPPPzLAdQ_30, "len(a) == L seq modified while iterating over it", 48);
static N_NIMCALL(void, Marker_tyRef_VgLrzdOR3HwTOOL2IcFN9cA)(void* p, NI op) {
	tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ* a;
	a = (tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, raiseEInvalidCsv_HcftpwJzOOP1xPgLVh0oUg)(NimStringDesc* filename, NI line, NI col, NimStringDesc* msg) {
	tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ* e;
	nimfr_("raiseEInvalidCsv", "parsecsv.nim");
	e = (tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*)0;
	nimln_(74, "parsecsv.nim");
	e = (tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*) newObj((&NTI_VgLrzdOR3HwTOOL2IcFN9cA_), sizeof(tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI_5MMHYN9cM2d1GsHy5O9agEIQ_);
	nimln_(75, "parsecsv.nim");
	{
		NimStringDesc* T5_;
		if (!((filename ? filename->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(76, "parsecsv.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = rawNewString(msg->Sup.len + 7);
appendString(T5_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_2));
appendString(T5_, msg);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.Sup.message), T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		NimStringDesc* T9_;
		nimln_(78, "parsecsv.nim");
		T7_ = (NimStringDesc*)0;
		T8_ = (NimStringDesc*)0;
		T8_ = nimIntToStr(line);
		T9_ = (NimStringDesc*)0;
		T9_ = nimIntToStr(col);
		T7_ = rawNewString(filename->Sup.len + T8_->Sup.len + T9_->Sup.len + msg->Sup.len + 12);
appendString(T7_, filename);
appendString(T7_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_3));
appendString(T7_, T8_);
appendString(T7_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_4));
appendString(T7_, T9_);
appendString(T7_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_5));
appendString(T7_, msg);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.Sup.message), T7_);
	}
	LA1_: ;
	nimln_(79, "parsecsv.nim");
	raiseException((Exception*)e, "CsvError");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, error_rSVZOSfuDbBAJ4HGxo0CdQ)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI pos, NimStringDesc* msg) {
	NI T1_;
	nimfr_("error", "parsecsv.nim");
	nimln_(82, "parsecsv.nim");
	T1_ = (NI)0;
	T1_ = getColNumber_9cj186ckGjLqyndkoW7bBdg((&(*my).Sup), pos);
	raiseEInvalidCsv_HcftpwJzOOP1xPgLVh0oUg((*my).filename, (*my).Sup.lineNumber, T1_, msg);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, open_dmBuwTCvdiT9cdjydWhbTTg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("open", "parsecsv.nim");
	nimln_(99, "parsecsv.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	open_xmgaYJZNnO6QcDtac9bs3Vg(T1_, input, ((NI) 8192), TM_3rBY6NOHI29c34PPPPzLAdQ_6);
	nimln_(100, "parsecsv.nim");
	unsureAsgnRef((void**) (&(*my).filename), copyString(filename));
	nimln_(101, "parsecsv.nim");
	(*my).sep = separator;
	nimln_(102, "parsecsv.nim");
	(*my).quote = quote;
	nimln_(103, "parsecsv.nim");
	(*my).esc = escape;
	nimln_(104, "parsecsv.nim");
	(*my).skipWhite = skipInitialSpace;
	nimln_(105, "parsecsv.nim");
	unsureAsgnRef((void**) (&(*my).row), (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0));
	nimln_(106, "parsecsv.nim");
	(*my).currRow = ((NI) 0);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, open_grmoJIpX15R5Xfx6m2M1UA)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace) {
	tyObject_FileStreamObj_qoDM8xYRV40zbhS9acPNT9bw* s;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T6_;
	nimfr_("open", "parsecsv.nim");
	nimln_(112, "parsecsv.nim");
	s = newFileStream_9argyMqCIlB1KDaxUuYVcmw(filename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
	nimln_(113, "parsecsv.nim");
	{
		NimStringDesc* T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NimStringDesc*)0;
		T5_ = rawNewString(filename->Sup.len + 13);
appendString(T5_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_7));
appendString(T5_, filename);
		error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), ((NI) 0), T5_);
	}
	LA3_: ;
	nimln_(114, "parsecsv.nim");
	T6_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T6_ = &s->Sup;
	open_dmBuwTCvdiT9cdjydWhbTTg(my, T6_, filename, separator, quote, escape, skipInitialSpace);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(void, parseField_dP4vy9acfqJXAsuKp69aq8eQ)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc** a) {
	NI pos;
	NCSTRING buf;
	nimfr_("parseField", "parsecsv.nim");
	nimln_(118, "parsecsv.nim");
	pos = (*my).Sup.bufpos;
	nimln_(119, "parsecsv.nim");
	buf = (*my).Sup.buf;
	nimln_(120, "parsecsv.nim");
	{
		if (!(*my).skipWhite) goto LA3_;
		{
			nimln_(121, "parsecsv.nim");
			while (1) {
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_8;
				if (!(((NU8)(buf[pos])) == ((NU8)(32)) || ((NU8)(buf[pos])) == ((NU8)(9)))) goto LA6;
				TM_3rBY6NOHI29c34PPPPzLAdQ_8 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_8);
			} LA6: ;
		}
	}
	LA3_: ;
	nimln_(122, "parsecsv.nim");
	(*a) = setLengthStr((*a), ((NI) 0));
	nimln_(123, "parsecsv.nim");
	{
		NIM_BOOL T9_;
		NI TM_3rBY6NOHI29c34PPPPzLAdQ_9;
		T9_ = (NIM_BOOL)0;
		T9_ = ((NU8)(buf[pos]) == (NU8)((*my).quote));
		if (!(T9_)) goto LA10_;
		nimln_(398, "system.nim");
		nimln_(123, "parsecsv.nim");
		T9_ = !(((NU8)((*my).quote) == (NU8)(0)));
		LA10_: ;
		if (!T9_) goto LA11_;
		nimln_(124, "parsecsv.nim");
		TM_3rBY6NOHI29c34PPPPzLAdQ_9 = addInt(pos, ((NI) 1));
		pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_9);
		{
			nimln_(125, "parsecsv.nim");
			while (1) {
				NIM_CHAR c;
				nimln_(126, "parsecsv.nim");
				c = buf[pos];
				nimln_(127, "parsecsv.nim");
				{
					NimStringDesc* T19_;
					if (!((NU8)(c) == (NU8)(0))) goto LA17_;
					nimln_(128, "parsecsv.nim");
					(*my).Sup.bufpos = pos;
					nimln_(129, "parsecsv.nim");
					T19_ = (NimStringDesc*)0;
					T19_ = rawNewString(10);
appendChar(T19_, (*my).quote);
appendString(T19_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_10));
					error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), pos, T19_);
					nimln_(130, "parsecsv.nim");
					goto LA13;
				}
				goto LA15_;
				LA17_: ;
				{
					nimln_(131, "parsecsv.nim");
					if (!((NU8)(c) == (NU8)((*my).quote))) goto LA21_;
					nimln_(132, "parsecsv.nim");
					{
						NIM_BOOL T25_;
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_11;
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_12;
						T25_ = (NIM_BOOL)0;
						T25_ = ((NU8)((*my).esc) == (NU8)(0));
						if (!(T25_)) goto LA26_;
						TM_3rBY6NOHI29c34PPPPzLAdQ_11 = addInt(pos, ((NI) 1));
						T25_ = ((NU8)(buf[(NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_11)]) == (NU8)((*my).quote));
						LA26_: ;
						if (!T25_) goto LA27_;
						nimln_(133, "parsecsv.nim");
						(*a) = addChar((*a), (*my).quote);
						nimln_(134, "parsecsv.nim");
						TM_3rBY6NOHI29c34PPPPzLAdQ_12 = addInt(pos, ((NI) 2));
						pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_12);
					}
					goto LA23_;
					LA27_: ;
					{
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_13;
						nimln_(136, "parsecsv.nim");
						TM_3rBY6NOHI29c34PPPPzLAdQ_13 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_13);
						nimln_(137, "parsecsv.nim");
						goto LA13;
					}
					LA23_: ;
				}
				goto LA15_;
				LA21_: ;
				{
					NI TM_3rBY6NOHI29c34PPPPzLAdQ_14;
					NI TM_3rBY6NOHI29c34PPPPzLAdQ_15;
					nimln_(138, "parsecsv.nim");
					if (!((NU8)(c) == (NU8)((*my).esc))) goto LA31_;
					nimln_(139, "parsecsv.nim");
					TM_3rBY6NOHI29c34PPPPzLAdQ_14 = addInt(pos, ((NI) 1));
					(*a) = addChar((*a), buf[(NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_14)]);
					nimln_(140, "parsecsv.nim");
					TM_3rBY6NOHI29c34PPPPzLAdQ_15 = addInt(pos, ((NI) 2));
					pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_15);
				}
				goto LA15_;
				LA31_: ;
				{
					nimln_(142, "parsecsv.nim");
					switch (((NU8)(c))) {
					case 13:
					{
						tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T35_;
						nimln_(144, "parsecsv.nim");
						T35_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
						T35_ = &my->Sup;
						pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T35_, pos);
						nimln_(145, "parsecsv.nim");
						buf = (*my).Sup.buf;
						nimln_(146, "parsecsv.nim");
						(*a) = resizeString((*a), 1);
appendString((*a), ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_16));
					}
					break;
					case 10:
					{
						tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T37_;
						nimln_(148, "parsecsv.nim");
						T37_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
						T37_ = &my->Sup;
						pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T37_, pos);
						nimln_(149, "parsecsv.nim");
						buf = (*my).Sup.buf;
						nimln_(150, "parsecsv.nim");
						(*a) = resizeString((*a), 1);
appendString((*a), ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_16));
					}
					break;
					default:
					{
						NI TM_3rBY6NOHI29c34PPPPzLAdQ_17;
						nimln_(152, "parsecsv.nim");
						(*a) = addChar((*a), c);
						nimln_(153, "parsecsv.nim");
						TM_3rBY6NOHI29c34PPPPzLAdQ_17 = addInt(pos, ((NI) 1));
						pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_17);
					}
					break;
					}
				}
				LA15_: ;
			}
		} LA13: ;
	}
	goto LA7_;
	LA11_: ;
	{
		{
			nimln_(155, "parsecsv.nim");
			while (1) {
				NIM_CHAR c_2;
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_18;
				nimln_(156, "parsecsv.nim");
				c_2 = buf[pos];
				nimln_(157, "parsecsv.nim");
				{
					if (!((NU8)(c_2) == (NU8)((*my).sep))) goto LA44_;
					goto LA40;
				}
				LA44_: ;
				nimln_(158, "parsecsv.nim");
				{
					if (!(((NU8)(c_2)) == ((NU8)(13)) || ((NU8)(c_2)) == ((NU8)(10)) || ((NU8)(c_2)) == ((NU8)(0)))) goto LA48_;
					goto LA40;
				}
				LA48_: ;
				nimln_(159, "parsecsv.nim");
				(*a) = addChar((*a), c_2);
				nimln_(160, "parsecsv.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_18 = addInt(pos, ((NI) 1));
				pos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_18);
			}
		} LA40: ;
	}
	LA7_: ;
	nimln_(161, "parsecsv.nim");
	(*my).Sup.bufpos = pos;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, processedRows_B9bl8htcg8N29c8FQEl079aPg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	NI result;
	nimfr_("processedRows", "parsecsv.nim");
{	result = (NI)0;
	nimln_(165, "parsecsv.nim");
	result = (*my).currRow;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readRow_9bHdhFE0qEvOrDqjuQBz8Pw)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI columns) {
	NIM_BOOL result;
	NI col;
	NI oldpos;
	NI TM_3rBY6NOHI29c34PPPPzLAdQ_27;
	nimfr_("readRow", "parsecsv.nim");
	result = (NIM_BOOL)0;
	nimln_(173, "parsecsv.nim");
	col = ((NI) 0);
	nimln_(174, "parsecsv.nim");
	oldpos = (*my).Sup.bufpos;
	{
		nimln_(175, "parsecsv.nim");
		while (1) {
			NI oldlen;
			NI T3_;
			NI TM_3rBY6NOHI29c34PPPPzLAdQ_22;
			nimln_(398, "system.nim");
			nimln_(175, "parsecsv.nim");
			if (!!(((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)(0)))) goto LA2;
			nimln_(176, "parsecsv.nim");
			T3_ = ((*my).row ? (*my).row->Sup.len : 0);
			oldlen = T3_;
			nimln_(177, "parsecsv.nim");
			{
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_19;
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_20;
				NimStringDesc* T8_;
				TM_3rBY6NOHI29c34PPPPzLAdQ_19 = addInt(col, ((NI) 1));
				if (!(oldlen < (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_19))) goto LA6_;
				nimln_(178, "parsecsv.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_20 = addInt(col, ((NI) 1));
				(*my).row = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*my).row)->Sup, sizeof(NimStringDesc*), ((NI)chckRange((NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_20), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				if ((NU)(col) >= (NU)((*my).row->Sup.len)) raiseIndexError();
				nimln_(179, "parsecsv.nim");
				T8_ = (NimStringDesc*)0;
				T8_ = (*my).row->data[col]; (*my).row->data[col] = copyStringRC1(((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_21));
				if (T8_) nimGCunrefNoCycle(T8_);
			}
			LA6_: ;
			nimln_(180, "parsecsv.nim");
			if ((NU)(col) >= (NU)((*my).row->Sup.len)) raiseIndexError();
			parseField_dP4vy9acfqJXAsuKp69aq8eQ(my, (&(*my).row->data[col]));
			nimln_(181, "parsecsv.nim");
			TM_3rBY6NOHI29c34PPPPzLAdQ_22 = addInt(col, ((NI) 1));
			col = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_22);
			nimln_(182, "parsecsv.nim");
			{
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_23;
				if (!((NU8)((*my).Sup.buf[(*my).Sup.bufpos]) == (NU8)((*my).sep))) goto LA11_;
				nimln_(183, "parsecsv.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_23 = addInt((*my).Sup.bufpos, ((NI) 1));
				(*my).Sup.bufpos = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_23);
			}
			goto LA9_;
			LA11_: ;
			{
				nimln_(185, "parsecsv.nim");
				switch (((NU8)((*my).Sup.buf[(*my).Sup.bufpos]))) {
				case 13:
				case 10:
				{
					{
						nimln_(188, "parsecsv.nim");
						while (1) {
							nimln_(189, "parsecsv.nim");
							switch (((NU8)((*my).Sup.buf[(*my).Sup.bufpos]))) {
							case 13:
							{
								tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T18_;
								nimln_(190, "parsecsv.nim");
								T18_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T18_ = &my->Sup;
								(*my).Sup.bufpos = handleCR_IwUEvMBOLRY9cqyar6XKEaw_2(T18_, (*my).Sup.bufpos);
							}
							break;
							case 10:
							{
								tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T20_;
								nimln_(191, "parsecsv.nim");
								T20_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T20_ = &my->Sup;
								(*my).Sup.bufpos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T20_, (*my).Sup.bufpos);
							}
							break;
							default:
							{
								nimln_(192, "parsecsv.nim");
								goto LA15;
							}
							break;
							}
						}
					} LA15: ;
				}
				break;
				case 0:
				{
				}
				break;
				default:
				{
					NimStringDesc* T24_;
					nimln_(194, "parsecsv.nim");
					T24_ = (NimStringDesc*)0;
					T24_ = rawNewString(10);
appendChar(T24_, (*my).sep);
appendString(T24_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_10));
					error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), (*my).Sup.bufpos, T24_);
				}
				break;
				}
				nimln_(195, "parsecsv.nim");
				goto LA1;
			}
			LA9_: ;
		} LA2: ;
	} LA1: ;
	nimln_(197, "parsecsv.nim");
	(*my).row = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*my).row)->Sup, sizeof(NimStringDesc*), ((NI)chckRange(col, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(198, "parsecsv.nim");
	result = (((NI) 0) < col);
	nimln_(199, "parsecsv.nim");
	{
		NIM_BOOL T27_;
		NIM_BOOL T28_;
		NI TM_3rBY6NOHI29c34PPPPzLAdQ_24;
		NimStringDesc* T33_;
		NimStringDesc* T34_;
		NimStringDesc* T35_;
		T27_ = (NIM_BOOL)0;
		T28_ = (NIM_BOOL)0;
		T28_ = result;
		if (!(T28_)) goto LA29_;
		nimln_(398, "system.nim");
		nimln_(199, "parsecsv.nim");
		T28_ = !((col == columns));
		LA29_: ;
		T27_ = T28_;
		if (!(T27_)) goto LA30_;
		T27_ = (((NI) 0) < columns);
		LA30_: ;
		if (!T27_) goto LA31_;
		nimln_(200, "parsecsv.nim");
		TM_3rBY6NOHI29c34PPPPzLAdQ_24 = addInt(oldpos, ((NI) 1));
		T33_ = (NimStringDesc*)0;
		T34_ = (NimStringDesc*)0;
		T34_ = nimIntToStr(columns);
		nimln_(201, "parsecsv.nim");
		T35_ = (NimStringDesc*)0;
		T35_ = nimIntToStr(col);
		T33_ = rawNewString(T34_->Sup.len + T35_->Sup.len + 37);
appendString(T33_, T34_);
appendString(T33_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_25));
appendString(T33_, T35_);
appendString(T33_, ((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_26));
		error_rSVZOSfuDbBAJ4HGxo0CdQ((&(*my)), (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_24), T33_);
	}
	LA31_: ;
	nimln_(202, "parsecsv.nim");
	TM_3rBY6NOHI29c34PPPPzLAdQ_27 = addInt((*my).currRow, ((NI) 1));
	(*my).currRow = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_27);
	popFrame();
	return result;
}

static N_INLINE(void, close_A55CxARYHkQe359a6AS5GRQparsecsv)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("close", "parsecsv.nim");
	nimln_(206, "parsecsv.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, readHeaderRow_8SSmlmR2zJJf2vnae2Ozsw)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	NIM_BOOL present;
	nimfr_("readHeaderRow", "parsecsv.nim");
	nimln_(211, "parsecsv.nim");
	present = readRow_9bHdhFE0qEvOrDqjuQBz8Pw(my, ((NI) 0));
	nimln_(212, "parsecsv.nim");
	{
		if (!present) goto LA3_;
		nimln_(213, "parsecsv.nim");
		genericSeqAssign((&(*my).headers), (*my).row, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_sPsD5Eb3qBZqwDJ6Yy4sNQparsecsv)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* a, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		NI L;
		NI T2_;
		i = (NimStringDesc*)0;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (a ? a->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_28;
				NI TM_3rBY6NOHI29c34PPPPzLAdQ_29;
				if (!(i_2 < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(a->Sup.len)) raiseIndexError();
				i = a->data[i_2];
				nimln_(2419, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA7_;
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(2420, "system.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_28 = addInt(result, ((NI) 1));
				result = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_28);
				nimln_(3809, "system.nim");
				TM_3rBY6NOHI29c34PPPPzLAdQ_29 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_3rBY6NOHI29c34PPPPzLAdQ_29);
				nimln_(3810, "system.nim");
				{
					NI T11_;
					T11_ = (a ? a->Sup.len : 0);
					if (!!((T11_ == L))) goto LA12_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3rBY6NOHI29c34PPPPzLAdQ_30));
				}
				LA12_: ;
			} LA4: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, rowEntry_A5sOKo5r9bzqQUyQAneitHg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* entry) {
	NimStringDesc** result;
	NI index;
	nimfr_("rowEntry", "parsecsv.nim");
	result = (NimStringDesc**)0;
	nimln_(220, "parsecsv.nim");
	index = find_sPsD5Eb3qBZqwDJ6Yy4sNQparsecsv((*my).headers, entry);
	nimln_(221, "parsecsv.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		nimln_(222, "parsecsv.nim");
		if ((NU)(index) >= (NU)((*my).row->Sup.len)) raiseIndexError();
		result = (&(*my).row->data[index]);
	}
	LA3_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvInit000)(void) {
	nimfr_("parsecsv", "parsecsv.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_parsecsvDatInit000)(void) {
static TNimNode* TM_3rBY6NOHI29c34PPPPzLAdQ_31[8];
static TNimNode TM_3rBY6NOHI29c34PPPPzLAdQ_0[10];
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.size = sizeof(tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ);
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.kind = 17;
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.base = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[0].len = 0; TM_3rBY6NOHI29c34PPPPzLAdQ_0[0].kind = 2;
NTI_5MMHYN9cM2d1GsHy5O9agEIQ_.node = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[0];
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.size = sizeof(tyObject_CsvError_5MMHYN9cM2d1GsHy5O9agEIQ*);
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.kind = 22;
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.base = (&NTI_5MMHYN9cM2d1GsHy5O9agEIQ_);
NTI_VgLrzdOR3HwTOOL2IcFN9cA_.marker = Marker_tyRef_VgLrzdOR3HwTOOL2IcFN9cA;
NTI_e0KmhL4ItditGQKnCUZMoQ_.size = sizeof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ);
NTI_e0KmhL4ItditGQKnCUZMoQ_.kind = 17;
NTI_e0KmhL4ItditGQKnCUZMoQ_.base = (&NTI_B6cGbTPhMsqMovc9cOcIHRw_);
TM_3rBY6NOHI29c34PPPPzLAdQ_31[0] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[2];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[2].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[2].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, row);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[2].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[2].name = "row";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[1] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[3];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[3].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[3].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, filename);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[3].name = "filename";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[2] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[4];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[4].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[4].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, sep);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[4].typ = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[4].name = "sep";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[3] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[5];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[5].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[5].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, quote);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[5].typ = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[5].name = "quote";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[4] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[6];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[6].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[6].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, esc);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[6].typ = (&NTI_nmiMWKVIe46vacnhAFrQvw_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[6].name = "esc";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[5] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[7];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[7].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[7].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, skipWhite);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[7].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[7].name = "skipWhite";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[6] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[8];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[8].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[8].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, currRow);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[8].name = "currRow";
TM_3rBY6NOHI29c34PPPPzLAdQ_31[7] = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[9];
TM_3rBY6NOHI29c34PPPPzLAdQ_0[9].kind = 1;
TM_3rBY6NOHI29c34PPPPzLAdQ_0[9].offset = offsetof(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ, headers);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[9].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_3rBY6NOHI29c34PPPPzLAdQ_0[9].name = "headers";
TM_3rBY6NOHI29c34PPPPzLAdQ_0[1].len = 8; TM_3rBY6NOHI29c34PPPPzLAdQ_0[1].kind = 2; TM_3rBY6NOHI29c34PPPPzLAdQ_0[1].sons = &TM_3rBY6NOHI29c34PPPPzLAdQ_31[0];
NTI_e0KmhL4ItditGQKnCUZMoQ_.node = &TM_3rBY6NOHI29c34PPPPzLAdQ_0[1];
}

